import fs from "fs";
import path from "path";
import os from "os";
import crypto from "crypto";
import { chmod } from "fs/promises";
import { pipeline } from "stream/promises";
import youtubedl from "youtube-dl-exec";
import ytdl from "@distube/ytdl-core";

function convertToNetscape(content) {
  if (!content) return "";
  if (content.trim().startsWith("[")) {
    try {
      const parsed = JSON.parse(content);
      if (Array.isArray(parsed)) {
        let netscape = "";
        for (const c of parsed) {
          const domain = c.domain || "";
          const flag = domain.startsWith(".") ? "TRUE" : "FALSE";
          const path = c.path || "/";
          const secure = c.secure ? "TRUE" : "FALSE";
          const expiration = c.expirationDate ? Math.round(c.expirationDate) : 0;
          const name = c.name || "";
          const value = c.value || "";
          netscape += `${domain}\t${flag}\t${path}\t${secure}\t${expiration}\t${name}\t${value}\n`;
        }
        return netscape;
      }
    } catch (e) {
      console.warn("[get-yt-dlp] Failed parsing JSON in convertToNetscape:", e.message);
    }
  }
  return content.trim() + "\n";
}

export function writeCookiesFile() {
  try {
    let cookiesContent = "# Netscape HTTP Cookie File\n# Generated by media-fetcher\n";
    let hasCookies = false;

    // YouTube
    const ytB64 = process.env.YOUTUBE_COOKIES_B64;
    const ytRaw = process.env.YOUTUBE_COOKIES;
    let ytContent = "";
    if (ytB64) {
      ytContent = Buffer.from(ytB64.trim(), "base64").toString("utf-8");
    } else if (ytRaw) {
      ytContent = ytRaw.trim();
    }
    if (ytContent) {
      cookiesContent += convertToNetscape(ytContent);
      hasCookies = true;
    }

    // Instagram
    const igB64 = process.env.INSTAGRAM_COOKIES_B64;
    const igRaw = process.env.INSTAGRAM_COOKIES;
    let igContent = "";
    if (igB64) {
      igContent = Buffer.from(igB64.trim(), "base64").toString("utf-8");
    } else if (igRaw) {
      igContent = igRaw.trim();
    }
    if (igContent) {
      cookiesContent += convertToNetscape(igContent);
      hasCookies = true;
    }

    if (!hasCookies) {
      console.log("[get-yt-dlp] No cookies environment variables found.");
      return null;
    }

    const randomId = crypto.randomBytes(6).toString("hex");
    const cookiesPath = path.join(os.tmpdir(), `cookies-${randomId}.txt`);
    fs.writeFileSync(cookiesPath, cookiesContent, "utf-8");
    console.log(`[get-yt-dlp] Wrote cookies file to ${cookiesPath} (${cookiesContent.length} chars)`);
    return cookiesPath;
  } catch (err) {
    console.warn("[get-yt-dlp] Error writing cookies file:", err.message);
  }
  return null;
}

export function cleanupCookiesFile(cookiesPath) {
  if (cookiesPath && fs.existsSync(cookiesPath)) {
    try {
      fs.unlinkSync(cookiesPath);
      console.log(`[get-yt-dlp] Cleaned up temporary cookies file ${cookiesPath}`);
    } catch (e) {
      console.warn(`[get-yt-dlp] Failed to cleanup cookies file ${cookiesPath}:`, e.message);
    }
  }
}

export function getProxyUrl() {
  return process.env.YTDLP_PROXY_URL || process.env.HTTP_PROXY || process.env.HTTPS_PROXY || null;
}

export async function getYtDlpPath() {
  const isWin = process.platform === "win32";
  const primaryBin = isWin ? "yt-dlp.exe" : "yt-dlp";
  const tmpExecPath = path.join(os.tmpdir(), `exec-${primaryBin}`);

  // Return cached executable binary in /tmp if present
  if (fs.existsSync(tmpExecPath)) {
    return tmpExecPath;
  }

  // 1. Copy pre-bundled binary to /tmp (AWS Lambda / Vercel requires binaries in /tmp for execution permissions)
  const candidatePaths = [
    path.join(process.cwd(), "node_modules/youtube-dl-exec/bin", primaryBin),
    path.join(process.cwd(), "node_modules/youtube-dl-exec/bin", "yt-dlp"),
    path.join(process.cwd(), "node_modules/youtube-dl-exec/bin", "yt-dlp.exe"),
  ];

  for (const p of candidatePaths) {
    if (fs.existsSync(p)) {
      console.log(`[getYtDlpPath] Copying pre-bundled binary from ${p} to ${tmpExecPath}...`);
      try {
        fs.copyFileSync(p, tmpExecPath);
        if (!isWin) {
          fs.chmodSync(tmpExecPath, 0o755);
        }
        console.log(`[getYtDlpPath] Successfully prepared executable binary at ${tmpExecPath}`);
        return tmpExecPath;
      } catch (e) {
        console.warn(`[getYtDlpPath] Failed copying binary from ${p} to ${tmpExecPath}:`, e.message);
      }
    }
  }

  // 2. Download standalone binary to /tmp directory if pre-bundled binary not found
  console.log(`[getYtDlpPath] Downloading standalone binary to ${tmpExecPath}...`);
  const downloadUrl = isWin
    ? "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe"
    : "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux";

  const res = await fetch(downloadUrl);
  if (!res.ok || !res.body) {
    throw new Error(`Failed to download yt-dlp binary from ${downloadUrl}: ${res.statusText}`);
  }

  const fileStream = fs.createWriteStream(tmpExecPath);
  // @ts-ignore
  await pipeline(res.body, fileStream);

  if (!isWin) {
    try {
      await chmod(tmpExecPath, 0o755);
    } catch (e) {
      console.warn("[getYtDlpPath] chmod warning:", e.message);
    }
  }

  console.log(`[getYtDlpPath] Successfully downloaded binary to ${tmpExecPath}`);
  return tmpExecPath;
}

export async function runYtDlp(url, flags = {}) {
  const binPath = await getYtDlpPath();
  const instance = youtubedl.create(binPath);

  const cookiesPath = writeCookiesFile();
  const proxyUrl = getProxyUrl();

  const baseFlags = {
    dumpSingleJson: true,
    noWarnings: true,
    noCheckCertificates: true,
    preferFreeFormats: true,
    geoBypass: true,
    jsRuntimes: `node:${process.execPath}`,
    addHeader: [
      "referer:https://www.google.com/",
      "user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    ],
    ...(cookiesPath ? { cookies: cookiesPath } : {}),
    ...(proxyUrl ? { proxy: proxyUrl } : {}),
    ...flags,
  };

  if (cookiesPath) {
    console.log(`[runYtDlp] Extracting metadata using authenticated cookies file: ${cookiesPath}`);
  }

  try {
    return await instance(url, baseFlags);
  } finally {
    if (cookiesPath) {
      cleanupCookiesFile(cookiesPath);
    }
  }
}

export function getCookieAgent() {
  const b64Cookies = process.env.YOUTUBE_COOKIES_B64;
  const rawCookies = process.env.YOUTUBE_COOKIES;

  if (!b64Cookies && !rawCookies) return null;

  try {
    let content = "";
    if (b64Cookies) {
      content = Buffer.from(b64Cookies.trim(), "base64").toString("utf-8");
    } else if (rawCookies) {
      content = rawCookies.trim();
    }

    if (!content) return null;

    if (content.trim().startsWith("[")) {
      try {
        const parsed = JSON.parse(content);
        if (Array.isArray(parsed) && parsed.length > 0) {
          const cookieArray = parsed.map((c) => ({
            name: c.name || "",
            value: c.value || "",
            domain: c.domain || ".youtube.com",
            path: c.path || "/"
          }));
          console.log(`[getCookieAgent] Parsed ${cookieArray.length} JSON cookies for ytdl-core.`);
          return ytdl.createAgent(cookieArray);
        }
      } catch (e) {
        console.warn("[getCookieAgent] Failed parsing JSON cookies for ytdl-core:", e.message);
      }
    }

    const cookieArray = [];
    const lines = content.split("\n");
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const parts = trimmed.split("\t");
      if (parts.length >= 7) {
        cookieArray.push({
          name: parts[5],
          value: parts[6],
          domain: parts[0],
          path: parts[2]
        });
      }
    }

    if (cookieArray.length > 0) {
      console.log(`[getCookieAgent] Parsed ${cookieArray.length} cookies for ytdl-core.`);
      return ytdl.createAgent(cookieArray);
    }
  } catch (err) {
    console.warn("[getCookieAgent] Error parsing cookies for ytdl-core:", err.message);
  }
  return null;
}

export function getCookieHeaderString(targetUrl) {
  if (!targetUrl) return "";

  try {
    const u = new URL(targetUrl);
    const isYoutubeCdn = u.hostname.includes("googlevideo.com") || u.hostname.includes("youtube.com") || u.hostname.includes("youtu.be");
    const isInstagramCdn = u.hostname.includes("instagram.com") || u.hostname.includes("cdninstagram.com");

    let b64Cookies = "";
    let rawCookies = "";

    if (isYoutubeCdn) {
      b64Cookies = process.env.YOUTUBE_COOKIES_B64;
      rawCookies = process.env.YOUTUBE_COOKIES;
    } else if (isInstagramCdn) {
      b64Cookies = process.env.INSTAGRAM_COOKIES_B64;
      rawCookies = process.env.INSTAGRAM_COOKIES;
    }

    if (!b64Cookies && !rawCookies) return "";

    let content = "";
    if (b64Cookies) {
      content = Buffer.from(b64Cookies.trim(), "base64").toString("utf-8");
    } else if (rawCookies) {
      content = rawCookies.trim();
    }

    if (!content) return "";

    const cookies = [];
    if (content.trim().startsWith("[")) {
      try {
        const parsed = JSON.parse(content);
        if (Array.isArray(parsed)) {
          for (const c of parsed) {
            if (c.name && c.value) {
              cookies.push(`${c.name}=${c.value}`);
            }
          }
        }
      } catch (e) {
        console.warn("[get-yt-dlp] Failed parsing JSON cookies in getCookieHeaderString:", e.message);
      }
    } else {
      const lines = content.split("\n");
      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith("#")) continue;
        const parts = trimmed.split("\t");
        if (parts.length >= 7) {
          cookies.push(`${parts[5]}=${parts[6]}`);
        }
      }
    }

    return cookies.join("; ");
  } catch (err) {
    console.warn("[get-yt-dlp] Error generating cookie header string:", err.message);
  }
  return "";
}
